name: "Get version from tag"
description: "Get version number from GitHub release tag name"

branding:
  icon: "git-branch"
  color: "blue"

inputs:
  format:
    description: 'Format of the version number'
    required: true
    default: 'default'

outputs:
  version:
    description: "Version number parsed from GitHub release tag name"

runs:
  using: "node20"
  main: "dist/index.js"
